name: deploy

on:

  push:
  
    branches: [ main ]

  workflow_dispatch:


jobs:

  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2.3.1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
