name: Test

on: [push, pull_request, workflow_dispatch]


jobs:

  tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt-get install jq python3 python3-pip firefox && pip3 install -r requirements.txt
      
      - name: HTML Validation
        run: |
          ./tests/validators/html_validator.sh public
          
      - name: CSS Validation
        run: |
          ./tests/validators/css_validator.sh public

      - name: Selenium Tests
        run: |
          cd tests/webtests
          python3 -m unittest -v
